from pirates.distributed.DistributedInteractiveAI import DistributedInteractiveAI
from pirates.shipparts.DistributedShippartAI import DistributedShippartAI

class DistributedSteeringWheelAI(DistributedInteractiveAI, DistributedShippartAI):
    pass
