from pirates.distributed.DistributedInteractiveAI import DistributedInteractiveAI
from pirates.distributed.DistributedTargetableObjectAI import DistributedTargetableObjectAI

class DistributedInteractivePropAI(DistributedInteractiveAI, DistributedTargetableObjectAI):
    pass
